### ISSUE TITLE
Esri.ArcGISRuntime.Toolkit.WPF - version 100.2.0-beta3.42.g654578e5e6

### ISSUE THREAD

**Issue by bigend** [Esri/mapbook-wpf#26]
I am just trying to build version upgraded to to 100.2 and there is reference to Esri.ArcGISRuntime.Toolkit.WPF - version 100.2.0-beta3.42.g654578e5e6. But the latest version I could find so far is 100.1.0-beta2 and that one is obviously not working well. Is that 100.2.0-beta available somewhere?

**Comment by marastoica** [comment]
This is a nuget package hosted on AppVeyor. To add it to your project, add https://ci.appveyor.com/nuget/arcgis-toolkit-dotnet/ to your available package sources. I'm updating the doc now to reflect this info, thanks for pointing it out!

**Comment by bigend** [comment]
Thank you very much for prompt answer. I have added that reference to package sources. I am now able to build and debug the project and everything seems working fine, however I am getting this error from Package Manager:
"'100.2.0-beta3.42.g654578e5e6' is not a valid version string.
Parameter name: version"
I guess I can live with that, I just thought you should know. 
Thank you.

**Comment by marastoica** [comment]
Thanks for confirming this is working. As far as the version error, that should all go away when the toolkit is out of beta.
