### ISSUE TITLE
"Invalid ArcGISRuntime deployment" error with 100.9

### ISSUE THREAD

**Issue by lXie208** [Esri/mapbook-wpf#45]
Got the following error with 100.9 in VS 2017:

![image](https://user-images.githubusercontent.com/52176718/98123978-98045500-1e80-11eb-93e3-8122cea5d0e0.png)

The app did get through when I switch to 100.8.

**Comment by nCastle1** [comment]
@lXie208 I was able to reproduce locally. I've pushed a fix for the issue in this PR: https://github.com/Esri/mapbook-wpf/pull/46

Please let me know if this resolves your issue. Thank you!

**Comment by lXie208** [comment]
> @lXie208 I was able to reproduce locally. I've pushed a fix for the issue in this PR: #46
> 
> Please let me know if this resolves your issue. Thank you!

This resolves the issue. Thank you so much!
